### ISSUE TITLE
Issue when submitting code

### ISSUE THREAD

**Issue by iperez319** [Komosa/cf#1]
- I downloaded the binary and added to my PATH
- I logged on successfully
-  The issue occurs when I call `cf submission.cpp -prob=845a`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x403191]

goroutine 1 [running]:
panic(0x7ccf40, 0xc08200e080)
        /home/kokos/.goinstallation/src/runtime/panic.go:481 +0x3f4
main.formAction(0x0, 0x0, 0x0)
        /home/kokos/gocode/src/github.com/Komosa/cf/form.go:34 +0x1a1
main.(*cf).submit(0xc08200efb0, 0xc082006960, 0xe, 0x34d, 0xc08200efa5, 0x1, 0x1, 0x0, 0x0)
        /home/kokos/gocode/src/github.com/Komosa/cf/submit.go:128 +0x79b
main.run(0x0, 0x0)
        /home/kokos/gocode/src/github.com/Komosa/cf/main.go:118 +0x9c9
main.main()
        /home/kokos/gocode/src/github.com/Komosa/cf/main.go:34 +0x1f
```

**Comment by Komosa** [comment]
Are you logged via my app or web browser? (Must be via app :))
How long ago?


It is also possible, that problem is windows specific (I could check it later on windows machine).

Now, app is handling unlogged/expired attempts better, so I will be glad if you check with v1.1.2 ( win64 exe here: https://github.com/Komosa/cf_binaries )
